// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtoYwURWpd-yluTil8phw9n7lcOcoOxA',
    appId: '1:622112804735:web:7dc8e5dc146eed41d4d44a',
    messagingSenderId: '622112804735',
    projectId: 'food-couriers-a2052',
    authDomain: 'food-couriers-a2052.firebaseapp.com',
    storageBucket: 'food-couriers-a2052.appspot.com',
    measurementId: 'G-MEQ8FQTK76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4wJWpPpvxH5KjnfOIJX-ujAlMyF_dHs',
    appId: '1:622112804735:android:23001d4d0d8c8929d4d44a',
    messagingSenderId: '622112804735',
    projectId: 'food-couriers-a2052',
    storageBucket: 'food-couriers-a2052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhRpLLnUk2SiiyrJiTdQjsi0iUJnQ9Ec',
    appId: '1:622112804735:ios:276672732b2f423bd4d44a',
    messagingSenderId: '622112804735',
    projectId: 'food-couriers-a2052',
    storageBucket: 'food-couriers-a2052.appspot.com',
    iosBundleId: 'com.example.foodCouriers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnhRpLLnUk2SiiyrJiTdQjsi0iUJnQ9Ec',
    appId: '1:622112804735:ios:276672732b2f423bd4d44a',
    messagingSenderId: '622112804735',
    projectId: 'food-couriers-a2052',
    storageBucket: 'food-couriers-a2052.appspot.com',
    iosBundleId: 'com.example.foodCouriers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbtoYwURWpd-yluTil8phw9n7lcOcoOxA',
    appId: '1:622112804735:web:f15cde97e13828e5d4d44a',
    messagingSenderId: '622112804735',
    projectId: 'food-couriers-a2052',
    authDomain: 'food-couriers-a2052.firebaseapp.com',
    storageBucket: 'food-couriers-a2052.appspot.com',
    measurementId: 'G-H2L230KSNH',
  );
}
